In [1]:
print("hello world")

hello world


In [2]:
!pip3 install numpy

You should consider upgrading via the 'f:\python9.0\python.exe -m pip install --upgrade pip' command.


In [3]:
import numpy as np

In [7]:
arr = np.array([1,2,3])

In [8]:
type(arr)

numpy.ndarray

In [9]:
arr.shape

(3,)

In [10]:
c=np.zeros((3,4))

In [11]:
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.arange?

In [15]:
np.eye?

In [20]:
arr = np.array([[1, 2, 3, 4],
                [5, 2, 4, 2],
                [1, 2, 0, 1]])
newarr = arr.reshape(2,2,3)

In [21]:
newarr

array([[[1, 2, 3],
        [4, 5, 2]],

       [[4, 2, 1],
        [2, 0, 1]]])

In [23]:
newarr = arr.reshape(4,3)

In [24]:
newarr

array([[1, 2, 3],
       [4, 5, 2],
       [4, 2, 1],
       [2, 0, 1]])

In [25]:
arr = np.array([[-1,2,0,4],
               [4,-0.5,6,0],
               [2.6,0,7,8],
               [3,-7,4,2.0]])

In [26]:
arr

array([[-1. ,  2. ,  0. ,  4. ],
       [ 4. , -0.5,  6. ,  0. ],
       [ 2.6,  0. ,  7. ,  8. ],
       [ 3. , -7. ,  4. ,  2. ]])

In [27]:
arr[1::2, :3:2]

array([[4., 6.],
       [3., 4.]])

In [28]:
a=np.array([1,2,5,3])

In [29]:
a+1

array([2, 3, 6, 4])

In [30]:
a.T

array([1, 2, 5, 3])